# app specific settings
app:
  destination_queue: testq
  version: ${project.version}


# Spring boot - overriding settings
spring:
  activemq:
    broker-url: tcp://10.28.60.243:61616
    user: admin
    password: admin
    in-memory: true 
    pooled: false
  thymeleaf:
    cache: false
  profiles:
    active: development
#embedded h2 database properties
  datasource:
    url: jdbc:h2:mem:playpen;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=true
    driverClassName: org.h2.Driver

  
#overriding embedded server properties
server:
  port: 8081
  context-path: /salesMaster



# application specific properties not overrides for spring boot opinions
#jenkins detail
jenkins:
  api:
     url: http://10.30.188.80:8777/jenkins/api/xml

#mas specific jenkins jobs
mas:
  jobs:
    prefix: MAS
   
ssl:
  port: 8084
---
#next yaml document
 